const BASE_PROMPT=`Ты являешься глазами незрячего человека. Посмотри на изображение с камеры смартфона. Коротко опиши всё важное, что находится перед человеком. Особое внимание: люди, транспорт, двери, лестницы, бордюры, стены, мебель, предметы на пути, препятствия, животные, заметный текст и потенциально опасные объекты. Используй слова впереди, слева, справа, сверху, снизу, рядом, далеко. Не выдумывай расстояние. Не перечисляй несущественные детали. Говори по-русски непосредственно пользователю. Не начинай словами «На изображении видно». Если явно видна опасность, начни с «Осторожно». Если заметен текст, в конце добавь «Вижу текст. Нажмите кнопку Прочитать».`;
const detailInstruction={short:'Ответ — одно короткое предложение.',normal:'Ответ — максимум два коротких предложения.',detailed:'Ответ — максимум три коротких предложения.'};
const prompt=detail=>`${BASE_PROMPT}\n${detailInstruction[detail]??detailInstruction.normal}`;
function imageUrl(bytes){return`data:image/jpeg;base64,${bytes.toString('base64')}`}
async function request(url,options,signal){const response=await fetch(url,{...options,signal});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error(`Некорректный ответ ${response.status}`)}if(!response.ok)throw new Error(data?.error?.message??data?.error??`${response.status}`);return data}
export class GeminiVisionProvider{providerName='Gemini';isAvailable(){return!!process.env.GEMINI_API_KEY}async analyzeImage(bytes,detail,signal){const model=process.env.GEMINI_MODEL||'gemini-2.5-flash';const data=await request(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt(detail)},{inline_data:{mime_type:'image/jpeg',data:bytes.toString('base64')}}]}],generationConfig:{temperature:.2,maxOutputTokens:220}})},signal);return data.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join(' ').trim()}}
class OpenAiCompatibleProvider{constructor(name,url,keyEnv,modelEnv){this.providerName=name;this.url=url;this.keyEnv=keyEnv;this.modelEnv=modelEnv}isAvailable(){return!!process.env[this.keyEnv]&&!!process.env[this.modelEnv]}async analyzeImage(bytes,detail,signal){const data=await request(this.url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env[this.keyEnv]}`,...(this.providerName==='OpenRouter'?{'HTTP-Referer':process.env.PUBLIC_APP_URL||'https://qraft-vision.onrender.com','X-Title':'Qraft Vision'}:{})},body:JSON.stringify({model:process.env[this.modelEnv],messages:[{role:'user',content:[{type:'text',text:prompt(detail)},{type:'image_url',image_url:{url:imageUrl(bytes)}}]}],temperature:.2,max_tokens:220})},signal);return data.choices?.[0]?.message?.content?.trim()}}
export class OpenRouterVisionProvider extends OpenAiCompatibleProvider{constructor(){super('OpenRouter','https://openrouter.ai/api/v1/chat/completions','OPENROUTER_API_KEY','OPENROUTER_MODEL')}}
export class HuggingFaceVisionProvider extends OpenAiCompatibleProvider{constructor(){super('Hugging Face','https://router.huggingface.co/v1/chat/completions','HF_TOKEN','HF_VISION_MODEL')}}
export class MockVisionProvider{providerName='Mock';isAvailable(){return process.env.ALLOW_MOCK_VISION==='true'}async analyzeImage(){return'Тестовое описание сцены.'}}
export class ProviderChain{constructor(providers){this.providers=providers}async analyzeImage(bytes,detail,signal){const errors=[];for(const provider of this.providers){if(!provider.isAvailable())continue;try{const description=await provider.analyzeImage(bytes,detail,signal);if(description)return{description,providerName:provider.providerName}}catch(error){if(signal.aborted)throw error;errors.push(`${provider.providerName}: ${error.message}`)}}if(!this.providers.some(p=>p.isAvailable()))throw new Error('AI provider не настроен');throw new Error(`Все AI providers недоступны. ${errors.join('; ')}`)}}
