import type{BoundingBox,Detection,Direction,Priority,Proximity,SceneDescriptionProvider}from'../types';
export const RU_LABELS:Record<string,string>={person:'человек',bicycle:'велосипед',car:'автомобиль',motorcycle:'мотоцикл',bus:'автобус',truck:'грузовик',dog:'собака',cat:'кошка',chair:'стул','dining table':'стол',bottle:'бутылка',cup:'кружка',backpack:'рюкзак',handbag:'сумка',suitcase:'чемодан',bench:'скамейка','traffic light':'светофор','stop sign':'знак «Стоп»'};
const HIGH=new Set(['person','bicycle','car','motorcycle','bus','truck']);const MEDIUM=new Set(['chair','dining table','bench','suitcase']);
export function directionFromBox(box:BoundingBox,frameWidth:number):Direction{const center=(box.x+box.width/2)/frameWidth;return center<.36?'слева':center>.64?'справа':'впереди'}
export function proximityFromBox(box:BoundingBox,frameWidth:number,frameHeight:number):Proximity{const area=box.width*box.height/(frameWidth*frameHeight);return area>.38?'очень близко':area>.16?'близко':area>.045?'впереди':'дальше'}
export function priorityFor(label:string,direction:Direction,proximity:Proximity):Priority{return HIGH.has(label)&&(direction==='впереди'||proximity==='очень близко')?'high':MEDIUM.has(label)||HIGH.has(label)?'medium':'low'}
export function detectionPhrase(d:Detection):string{const where=d.direction==='впереди'?(d.proximity==='очень близко'||d.proximity==='близко'?`${d.proximity} впереди`:'впереди'):d.direction;return `${d.label[0].toUpperCase()+d.label.slice(1)} ${where}`}
export function rank(d:Detection):number{return({high:3,medium:2,low:1})[d.priority]*100+d.score*10+(d.direction==='впереди'?5:0)}
export class LocalSceneProvider implements SceneDescriptionProvider{async describe(ds:Detection[],text?:string){if(!ds.length&&!text)return'Объекты не распознаны';const items=[...ds].sort((a,b)=>rank(b)-rank(a)).slice(0,4).map(detectionPhrase);const scene=items.length?items.join('. '):'';return[scene,text?`Текст: ${text}`:''].filter(Boolean).join('. ')}}
