import{registerSW}from'virtual:pwa-register';import{CameraController}from'./camera/camera';import{CocoVisionProvider}from'./providers/cocoProvider';import{ApiVisionProvider}from'./providers/remoteVisionProvider';import{SpeechService}from'./speech/speech';import{vibrate}from'./haptics/haptics';import{recognizeRussian}from'./ocr/ocr';import{AnnouncementGate}from'./utils/cooldown';import{detectionPhrase,LocalSceneProvider,rank}from'./utils/scene';import{isDangerDescription,textSimilarity}from'./utils/similarity';import{loadSettings,saveSettings}from'./settings/settings';import type{AppSettings,Detection,Priority}from'./types';
registerSW({immediate:true});
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id)as T;
const video=el<HTMLVideoElement>('camera'),canvas=el<HTMLCanvasElement>('captureCanvas'),camera=new CameraController(video,canvas),localVision=new CocoVisionProvider(),remoteVision=new ApiVisionProvider(),speech=new SpeechService(),localScene=new LocalSceneProvider();
let settings=loadSettings(),gate=new AnnouncementGate(settings.cooldownSeconds*1000),detections:Detection[]=[],localTimer:number|undefined,aiTimer:number|undefined,localBusy=false,aiBusy=false,obstacleMode=false,lastAiDescription='',lastAiSpokenAt=0,offlineAnnounced=false;
const status=el('status'),urgent=el('urgentStatus'),caption=el('visualCaption'),placeholder=el('cameraPlaceholder'),cameraButton=el<HTMLButtonElement>('cameraButton'),stopButton=el<HTMLButtonElement>('stopButton'),describeButton=el<HTMLButtonElement>('describeButton'),ocrButton=el<HTMLButtonElement>('ocrButton'),obstacleButton=el<HTMLButtonElement>('obstacleButton'),overlay=el('detectionOverlay'),debugPanel=el('debugPanel'),debugOutput=el('debugOutput');
function message(error:unknown){return error instanceof Error?error.message:'неизвестная ошибка'}
function setStatus(text:string,assertive=false){status.textContent=text;if(assertive){urgent.textContent='';requestAnimationFrame(()=>urgent.textContent=text)}}
function debug(data:Record<string,unknown>){if(!settings.debugEnabled)return;debugOutput.textContent=JSON.stringify({time:new Date().toLocaleTimeString('ru-RU'),...data},null,2)}
function say(text:string,priority:Priority='medium',assertive=false){speech.speak(text,priority);setStatus(text,assertive||priority==='high');if(priority!=='low')vibrate(priority,settings.hapticsEnabled)}
function apply(){speech.enabled=settings.speechEnabled;speech.rate=settings.speechRate;speech.language=settings.language;speech.voiceURI=settings.voiceURI;localVision.setThreshold(settings.sensitivity);gate.setCooldown(settings.cooldownSeconds*1000);debugPanel.hidden=!settings.debugEnabled;saveSettings(settings)}
async function analyzeLocal(force=false){if(localBusy||!camera.active||!settings.localDetectionEnabled||video.readyState<2)return;localBusy=true;try{detections=await localVision.detect(video);const important=[...detections].sort((a,b)=>rank(b)-rank(a)),top=important[0];if(!lastAiDescription)caption.textContent=top?detectionPhrase(top):'Локально значимые объекты не распознаны';overlay.classList.toggle('danger',top?.priority==='high');if(obstacleMode){const hazard=important.find(d=>d.direction==='впереди'&&['близко','очень близко'].includes(d.proximity)&&d.priority!=='low');if(hazard&&gate.shouldAnnounce(hazard)){say('Внимание. Распознанный объект прямо впереди','high',true);return}}if(top&&(force||gate.shouldAnnounce(top))){say(detectionPhrase(top),top.priority)}}catch(error){setStatus(`Локальное распознавание: ${message(error)}`,true)}finally{localBusy=false}}
async function analyzeAi(force=false){if(aiBusy||!camera.active||!settings.aiAnalysisEnabled)return;if(!remoteVision.isAvailable()){if(!offlineAnnounced){offlineAnnounced=true;say('Нет подключения к интернету. Быстрое распознавание продолжает работать.','medium')}debug({reason:'offline; AI skipped'});return}offlineAnnounced=false;aiBusy=true;const previous=lastAiDescription,controller=new AbortController(),timeout=window.setTimeout(()=>controller.abort(),15000);if(force)setStatus('Анализирую полную сцену…');try{const image=await camera.captureJpeg(960,.76),result=await remoteVision.analyzeImage(image,settings.detailLevel,controller.signal),similarity=textSimilarity(previous,result.description),danger=result.danger||isDangerDescription(result.description),elapsed=Date.now()-lastAiSpokenAt,cooldown=danger?1800:Math.max(3000,settings.cooldownSeconds*1000),changed=!previous||similarity<.62,shouldSpeak=force||danger||(changed&&elapsed>=cooldown);lastAiDescription=result.description;caption.textContent=result.description;if(shouldSpeak){say(result.description,danger?'high':'medium',danger);lastAiSpokenAt=Date.now()}else setStatus('Сцена почти не изменилась');debug({provider:result.providerName,latencyMs:result.latencyMs,current:result.description,previous,similarity:Number(similarity.toFixed(3)),danger,spoken:shouldSpeak,reason:force?'manual request':danger?'danger':!changed?'similar description':'cooldown'})}catch(error){const text=controller.signal.aborted?'AI не ответил вовремя. Быстрое распознавание продолжает работать.':`AI временно недоступен. ${message(error)}`;if(force)say(text,'medium');else setStatus(text);debug({error:message(error),previous,reason:'AI request failed'})}finally{clearTimeout(timeout);aiBusy=false}}
function schedule(){clearInterval(localTimer);clearInterval(aiTimer);if(camera.active&&settings.localDetectionEnabled)localTimer=window.setInterval(()=>void analyzeLocal(),1000/settings.frequency);if(camera.active&&settings.aiAnalysisEnabled&&settings.automaticDescription)aiTimer=window.setInterval(()=>void analyzeAi(),settings.aiIntervalSeconds*1000)}
async function start(){cameraButton.disabled=true;setStatus('Запрашиваю разрешение камеры…');try{await camera.start();placeholder.hidden=true;stopButton.disabled=describeButton.disabled=ocrButton.disabled=obstacleButton.disabled=false;el('modeBadge').textContent='Камера включена';say('Камера запущена.','low');if(settings.localDetectionEnabled){setStatus('Загружаю локальную модель…');await localVision.load();el('modelBadge').textContent='Локальный AI готов'}else el('modelBadge').textContent='Локальный AI выключен';setStatus('Камера работает');schedule();await Promise.allSettled([analyzeLocal(true),settings.automaticDescription?analyzeAi(true):Promise.resolve()])}catch(error){camera.stop();placeholder.hidden=false;cameraButton.disabled=false;setStatus(`Не удалось запустить: ${message(error)}. Проверьте разрешение камеры и HTTPS.`,true)}}
function stop(){clearInterval(localTimer);clearInterval(aiTimer);localTimer=aiTimer=undefined;camera.stop();speech.stop();placeholder.hidden=false;cameraButton.disabled=false;stopButton.disabled=describeButton.disabled=ocrButton.disabled=obstacleButton.disabled=true;caption.textContent='Нажмите «Запустить камеру»';el('modeBadge').textContent='Ожидание';lastAiDescription='';gate.reset();setStatus('Камера остановлена')}
cameraButton.onclick=()=>void start();stopButton.onclick=stop;describeButton.onclick=async()=>{if(settings.aiAnalysisEnabled&&remoteVision.isAvailable())await analyzeAi(true);else{await analyzeLocal(true);const text=await localScene.describe(detections);say(text)}};
ocrButton.onclick=async()=>{ocrButton.disabled=true;setStatus('Распознаю текст: 0%');try{const text=await recognizeRussian(camera.capture(1280),p=>setStatus(`Распознаю текст: ${Math.round(p*100)}%`));say(text?`Текст: ${text}`:'Текст не найден')}catch(error){setStatus(`OCR недоступен: ${message(error)}`,true)}finally{ocrButton.disabled=false}};
obstacleButton.onclick=()=>{obstacleMode=!obstacleMode;obstacleButton.setAttribute('aria-pressed',String(obstacleMode));el('modeBadge').textContent=obstacleMode?'Помощь при движении':'Камера включена';say(obstacleMode?'Экспериментальная помощь при движении включена':'Помощь при движении выключена')};
el<HTMLButtonElement>('repeatActionButton').onclick=()=>speech.repeat();el<HTMLButtonElement>('repeatButton').onclick=()=>speech.repeat();
const panel=el('settingsPanel'),settingsButton=el<HTMLButtonElement>('settingsButton');settingsButton.onclick=()=>{panel.hidden=!panel.hidden;settingsButton.setAttribute('aria-expanded',String(!panel.hidden))};
function bindCheck(id:keyof Pick<AppSettings,'speechEnabled'|'hapticsEnabled'|'automaticDescription'|'localDetectionEnabled'|'aiAnalysisEnabled'|'debugEnabled'>){const input=el<HTMLInputElement>(id);input.checked=settings[id];input.onchange=()=>{settings={...settings,[id]:input.checked};apply();if(camera.active)schedule()}}
function bindRange(id:string,key:keyof Pick<AppSettings,'speechRate'|'frequency'|'sensitivity'>,out:string,format=(v:number)=>String(v)){const input=el<HTMLInputElement>(id),output=el<HTMLOutputElement>(out);input.value=String(key==='sensitivity'?settings[key]*100:settings[key]);output.value=format(Number(input.value));input.oninput=()=>{const raw=Number(input.value),value=key==='sensitivity'?raw/100:raw;settings={...settings,[key]:value};output.value=format(raw);apply();if(key==='frequency'&&camera.active)schedule()}}
for(const id of['speechEnabled','hapticsEnabled','automaticDescription','localDetectionEnabled','aiAnalysisEnabled','debugEnabled']as const)bindCheck(id);bindRange('speechRate','speechRate','rateValue',v=>v.toFixed(1));bindRange('analysisFrequency','frequency','frequencyValue');bindRange('sensitivity','sensitivity','sensitivityValue',v=>`${v}%`);
function bindSelect<K extends keyof AppSettings>(id:string,key:K,parse:(value:string)=>AppSettings[K]=(v=>v as AppSettings[K])){const select=el<HTMLSelectElement>(id);select.value=String(settings[key]);select.onchange=()=>{settings={...settings,[key]:parse(select.value)};apply();if(camera.active)schedule()}}
bindSelect('cooldown','cooldownSeconds',Number);bindSelect('aiInterval','aiIntervalSeconds',Number);bindSelect('detailLevel','detailLevel');
const voiceSelect=el<HTMLSelectElement>('voiceSelect');function loadVoices(){const current=voiceSelect.value;voiceSelect.replaceChildren(new Option('Автоматически — русский',''));for(const voice of speech.getVoices().filter(v=>v.lang.toLowerCase().startsWith('ru')))voiceSelect.add(new Option(`${voice.name} (${voice.lang})`,voice.voiceURI));voiceSelect.value=current||settings.voiceURI}loadVoices();if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=loadVoices;voiceSelect.onchange=()=>{settings.voiceURI=voiceSelect.value;apply()};
apply();window.addEventListener('online',()=>{offlineAnnounced=false;setStatus('Подключение восстановлено')});window.addEventListener('offline',()=>void analyzeAi());document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInterval(localTimer);clearInterval(aiTimer);speech.stop()}else if(camera.active)schedule()});window.addEventListener('beforeunload',()=>{stop();localVision.dispose()});
