import'./style.css';import{registerSW}from'virtual:pwa-register';import{CameraController}from'./camera/camera';import{CocoVisionProvider}from'./providers/cocoProvider';import{SpeechService}from'./speech/speech';import{vibrate}from'./haptics/haptics';import{recognizeRussian}from'./ocr/ocr';import{AnnouncementGate}from'./utils/cooldown';import{detectionPhrase,LocalSceneProvider,rank}from'./utils/scene';import{loadSettings,saveSettings}from'./settings/settings';import type{AppSettings,Detection}from'./types';
registerSW({immediate:true});const el=<T extends HTMLElement>(id:string)=>document.getElementById(id)as T;const video=el<HTMLVideoElement>('camera'),canvas=el<HTMLCanvasElement>('captureCanvas'),camera=new CameraController(video,canvas),vision=new CocoVisionProvider(),speech=new SpeechService(),scene=new LocalSceneProvider();let settings=loadSettings(),gate=new AnnouncementGate(settings.cooldownSeconds*1000),detections:Detection[]=[],timer:number|undefined,busy=false,obstacleMode=false;
const status=el('status'),urgent=el('urgentStatus'),caption=el('visualCaption'),placeholder=el('cameraPlaceholder'),cameraButton=el<HTMLButtonElement>('cameraButton'),describeButton=el<HTMLButtonElement>('describeButton'),ocrButton=el<HTMLButtonElement>('ocrButton'),obstacleButton=el<HTMLButtonElement>('obstacleButton'),overlay=el('detectionOverlay');
function setStatus(text:string,assertive=false){status.textContent=text;if(assertive){urgent.textContent='';requestAnimationFrame(()=>urgent.textContent=text)}}function apply(){speech.enabled=settings.speechEnabled;speech.rate=settings.speechRate;speech.language=settings.language;vision.setThreshold(settings.sensitivity);gate.setCooldown(settings.cooldownSeconds*1000);saveSettings(settings)}
async function analyze(force=false){if(busy||!camera.active||video.readyState<2)return;busy=true;try{detections=await vision.detect(video);const important=[...detections].sort((a,b)=>rank(b)-rank(a));const top=important[0];caption.textContent=top?detectionPhrase(top):'Значимые объекты не распознаны';overlay.classList.toggle('danger',top?.priority==='high');if(obstacleMode){const hazard=important.find(d=>d.direction==='впереди'&&(d.proximity==='близко'||d.proximity==='очень близко')&&d.priority!=='low');if(hazard&&gate.shouldAnnounce(hazard)){const warning='Внимание. Препятствие впереди';speech.speak(warning,'high');vibrate('high',settings.hapticsEnabled);setStatus(warning,true);return}}if(top&&(force||gate.shouldAnnounce(top))){const text=detectionPhrase(top);speech.speak(text,top.priority);vibrate(top.priority,settings.hapticsEnabled);setStatus(text,top.priority==='high')}}catch(e){setStatus(`Ошибка распознавания: ${message(e)}`,true)}finally{busy=false}}
function schedule(){clearInterval(timer);timer=window.setInterval(()=>void analyze(),1000/settings.frequency)}function message(e:unknown){return e instanceof Error?e.message:'неизвестная ошибка'}
async function start(){cameraButton.disabled=true;setStatus('Запрашиваю разрешение камеры…');try{await camera.start();placeholder.hidden=true;cameraButton.querySelector('strong')!.textContent='Остановить камеру';describeButton.disabled=ocrButton.disabled=obstacleButton.disabled=false;el('modeBadge').textContent='Камера включена';setStatus('Загружаю локальную модель объектов…');await vision.load();el('modelBadge').textContent='COCO-SSD готов';setStatus('Камера работает. Анализ выполняется на устройстве');schedule();await analyze(true)}catch(e){camera.stop();placeholder.hidden=false;setStatus(`Не удалось запустить: ${message(e)}. Проверьте разрешение камеры и HTTPS.`,true)}finally{cameraButton.disabled=false}}
function stop(){clearInterval(timer);timer=undefined;camera.stop();speech.stop();placeholder.hidden=false;describeButton.disabled=ocrButton.disabled=obstacleButton.disabled=true;cameraButton.querySelector('strong')!.textContent='Запустить камеру';caption.textContent='Нажмите «Запустить камеру»';el('modeBadge').textContent='Ожидание';setStatus('Камера остановлена')}
cameraButton.onclick=()=>camera.active?stop():void start();describeButton.onclick=async()=>{setStatus('Описываю сцену…');await analyze(true);const text=await scene.describe(detections);speech.speak(text);setStatus(text)};ocrButton.onclick=async()=>{ocrButton.disabled=true;setStatus('Распознаю текст: 0%');try{const text=await recognizeRussian(camera.capture(),p=>setStatus(`Распознаю текст: ${Math.round(p*100)}%`));const result=text?`Текст: ${text}`:'Текст не найден';speech.speak(result);setStatus(result)}catch(e){setStatus(`OCR недоступен: ${message(e)}`,true)}finally{ocrButton.disabled=false}};obstacleButton.onclick=()=>{obstacleMode=!obstacleMode;obstacleButton.setAttribute('aria-pressed',String(obstacleMode));el('modeBadge').textContent=obstacleMode?'Помощь при движении':'Камера включена';const text=obstacleMode?'Экспериментальная помощь при движении включена':'Помощь при движении выключена';speech.speak(text);setStatus(text)};
const panel=el('settingsPanel'),settingsButton=el<HTMLButtonElement>('settingsButton');settingsButton.onclick=()=>{panel.hidden=!panel.hidden;settingsButton.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)el('settingsTitle').focus?.()};
function bindCheck(id:keyof Pick<AppSettings,'speechEnabled'|'hapticsEnabled'>){const input=el<HTMLInputElement>(id);input.checked=settings[id];input.onchange=()=>{settings={...settings,[id]:input.checked};apply()}}function bindRange(id:string,key:keyof Pick<AppSettings,'speechRate'|'frequency'|'sensitivity'>,out:string,format=(v:number)=>String(v)){const input=el<HTMLInputElement>(id),output=el<HTMLOutputElement>(out);input.value=String(key==='sensitivity'?settings[key]*100:settings[key]);output.value=format(Number(input.value));input.oninput=()=>{const raw=Number(input.value),value=key==='sensitivity'?raw/100:raw;settings={...settings,[key]:value};output.value=format(raw);apply();if(key==='frequency'&&camera.active)schedule()}}
bindCheck('speechEnabled');bindCheck('hapticsEnabled');bindRange('speechRate','speechRate','rateValue',v=>v.toFixed(1));bindRange('analysisFrequency','frequency','frequencyValue');bindRange('sensitivity','sensitivity','sensitivityValue',v=>`${v}%`);const cooldown=el<HTMLSelectElement>('cooldown');cooldown.value=String(settings.cooldownSeconds);cooldown.onchange=()=>{settings.cooldownSeconds=Number(cooldown.value);apply()};el<HTMLButtonElement>('repeatButton').onclick=()=>speech.repeat();apply();
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInterval(timer);speech.stop()}else if(camera.active)schedule()});window.addEventListener('beforeunload',()=>{stop();vision.dispose()});
